### ISSUE TITLE
How are we supposed to build this project

### ISSUE THREAD

**Issue by madebyshaurya** [vipinsaini0/Twitter_Clone_SwiftUI#7]
I cloned this in Xcode, added my own GooglePlist and then the error keeps coming up, "An attribute list can't appear here" and I can't edit the code because it's in one of the Firebase packages 
<img width="1043" alt="image" src="https://github.com/vipinsaini0/Twitter-Clone-SwiftUI/assets/74823287/7e10ce95-d554-4fc6-a0eb-95ceaba3202d">

**Comment by vipinsainitech** [comment]
let me check, I'll update you soon.

**Comment by madebyshaurya** [comment]
sounds good

**Comment by madebyshaurya** [comment]
> let me check, I'll update you soon.

Anything so far?

**Comment by vipinsainitech** [comment]
@Shaurya50211 
I checked the code by replacing the plist file with two new Firebase projects, and the project built successfully for both plist files.

try with updating pods file

**Comment by madebyshaurya** [comment]
I am using Xcode 15.0 beta do you thing that might be the issue and I don't understand why are we using pod files when this is already installed with spm

**Comment by Shaurya50211** [comment]
and I don't understand why are we using pod files when this is already installed with spm

**Comment by vipinsainitech** [comment]
xcode 15 might be possible, not sure

also remove pods and try again
closed the xcode project then

`pod deintegrate`
then remove workspace from project path and also remove pods related other file

**Comment by madebyshaurya** [comment]
what all firebase services did you download for this project

**Comment by madebyshaurya** [comment]
@vipinsaini0 will it be possible to vc on discord and for you to help me successfully build this project if not it's fine we can just chat on discord or github

**Comment by vipinsainitech** [comment]
As already mentioned on description, I used Firebase auth and Firestore.

**Comment by vipinsainitech** [comment]
As already mentioned on description, I used Firebase auth and Firestore.

**Comment by vipinsainitech** [comment]
hope issue will be solved?

**Comment by madebyshaurya** [comment]
i'm trying

**Comment by madebyshaurya** [comment]
sorry for asking but what is kingfisher dependency for if we are using firebase for everything?

**Comment by madebyshaurya** [comment]
@vipinsaini0 I tried reinstalling cocopods but it didn't work for me still have the error

**Comment by vipinsainitech** [comment]
> sorry for asking but what is kingfisher dependency for if we are using firebase for everything?

library for downloading and caching images from the web

> @vipinsaini0 I tried reinstalling cocopods but it didn't work for me still have the error

If you still facing error please try in xcode 14 as xcode 15 still in beta version

**Comment by madebyshaurya** [comment]
> 

I can't because i am using macOS sonoma on which xcode 14 can not run

**Comment by madebyshaurya** [comment]
It's fine thanks for helping out though I appreciate it

**Comment by vipinsainitech** [comment]
- Pods files removed and updated code committed.
-  For now, this project does not test in Xcode 15 beta, once Xcode 15 stable version released will check and update accordingly if require.

**As of now, closing this issue.**
